# -*- coding: utf-8 -*-
"""PythonCC.Chp3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bZm6qNWe4-NQoCFnnKH9wIiawwCQfJbh
"""

bicycles = ['trek', 'cannondale', 'redline', 'specialized'] #first list
print(bicycles)
#index positions start at 0, not 1
print("    " + bicycles[0].title())
print("\t" + bicycles[1].title())
print("\t\t" + bicycles[2].upper())
print("\t\t\t" + bicycles[3].title())
print(bicycles[-1], bicycles[-2])

message = "My first bicycle was a " + bicycles[2].title() + "."
print(message)

"""Try if yourself
* 3-1 Names
* 3-2 Greetings
* 3-3 Your Own List
"""

#3-1
names = ["Giuseppe", "Maisam", "Joe", "Devin", "Eddie"]
print(names[0],"\n",names[1],"\n",names[2],"\n",names[3],"\n",names[4])

#3-2
print("Hey " + names[0] + ", I hope you're having a great day!")
print("Hey " + names[1] + ", I hope you're having a great day!")
print("Hey " + names[2] + ", I hope you're having a great day!")
print("Hey " + names[3] + ", I hope you're having a great day!")
print("Hey " + names[4] + ", I hope you're having a great day!")

#3-3
stores = ['nordstroms', 'express', 'levis', 'north face', 'nike']
print("I use to go to West County mall all the time top shop at " + stores[-5].title())

motercycles = ['honda', 'yamaha', 'suzuki']
print(motercycles)

motercycles[0] = 'ducati' # here, we are changing the value stored in the first position of our motercycle list
print(motercycles)

"""Tensor flow fumbling around"""

import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))

