# -*- coding: utf-8 -*-
"""Chapter 3 Review 11-7-23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xeXk2BQKC5VC5E1XUrZx52UinNXJSc_v
"""

#3-1 - Store the names of a few of your freinds ina list called names. Print each person's name by accessing each element in the list, one at a time.
names = ['jake', 'martin', 'cody']
print(names[0].title())
print(names[1].title())
print(names[2].title())
print("\n")

#3-2 - Start with the list you used in Exercise 3-1, but instead of just printing each person's name, print a message to them. The test of each message should be the same, but each message should be personalized with the person's name.
for name in names:
  print(f"Hey {name.title()}, how are you today?")
print("\n")

#3-3 Think of your favorite mode of transportation, such as a motorcycle, or a car, and make a list that stored several examples. Use your list to print a series of statement about these items, such as "I would like to own a Honda motorcycle."
cars = ['honda', 'kia', 'bmw']
print(f"I would love to own a {cars[0].title()} one day")
print(f"I would love to own a {cars[1].title()} one day")
print(f"I would love to own a {cars[2].title()} one day")

