# -*- coding: utf-8 -*-
"""PythonCC Chp2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16SRvojEkKiRUp1RviIWXa6dAgu3ohN8y

Printing code & varous other methods() and functions
"""

variable = 'brandon knight '
print(variable.title().rstrip())

first_name = "brandon"
last_name = "knight"
full_name = first_name.title() + " " + last_name.title() #concatenation
print(full_name)

print("Languages:\n\tPython,\n\tC,\n\tJavaScript!")

message = "One of Python's strengths is its diverse community"
print(message)

"""Try it yourself

*   2-3 Personal Message
*   2-4 Name Cases
*   2-5 Famouse Quote
*   2-7 Stripping Names
"""

#2-3
first_name = "grace"
last_name = 'arnold'
full_name = first_name + " " + last_name
worker = full_name.title()
message = "Hello " + worker + " " + "what's new in the world of sustainability?"
print(message)

#2-4
worker_lower = full_name.lower()
print(worker_lower)
worker_upper = full_name.upper()
print(worker_upper)

#2-5
quote = "\"It doesn't matter how fast you're going, as long as you don't stop.\"" #notice, the \" created quotes in the printed line
philosoper = "the knight"
print(philosoper.title() + " " + "once said, " + quote)

#2-7
new_name = 'Name:\n\tbarb hall\t'
print(new_name.strip().title())
print(new_name.lstrip().title())
print(new_name.lstrip().title())

4**5 #exponent
3+1 #python will only display the last line of arithmatic unless asked otherwise
4.3 + 6.34

new_name2 = "brenelle"
age = 28
second_age = 18
message = "Happy " + str(age) + "th Birthday " + new_name2.title() + ", you don't look a day over " + str(second_age) + "!"
print(message)

"""Try it yourself
* 2-8 Number Eight
* 2-9 Favorite Number
"""

#2-8
print(4+4)
print(10-2)
print(16/2)
print(4*2)

#2-9
favorite_number = 23
message2 = "Did you know my favorite number is " + str(favorite_number) + "?"
print(message2)

import this #typing "import this" will display the Zen of Python, by Time Peters
